CREATE TABLE `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Paid_Media_Res`  (
  FECHA DATE,
  FUNNEL STRING,
  CAMPANIA STRING,
  CANAL STRING,
  MEDIO STRING,
  OBJETIVO STRING,
  BUDGET_RES NUMERIC,
  IMPRESIONES_RES INT64,
  VIEWS_RES INT64,
  CLICS_RES INT64,
  BOOKINGS_RES INT64,
  REVENUE_RES NUMERIC,
  LEADS_RES INT64,
  ORIGEN STRING
)
PARTITION BY FECHA
CLUSTER BY FUNNEL,CAMPANIA,CANAL,MEDIO  ;
