-- INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Paid_Media_Res`  


select DATE_TRUNC(Fecha,MONTH) AS FECHA,Funnel as FUNNEL, Campaign_funnel AS CAMPANIA,Canal AS CANAL, Medio AS MEDIO , '-' AS OBJETIVO, 
0 AS BUDGET_RES,0 AS IMPRESIONES_RES,0 AS VIEWS_RES,0 AS CLICS_RES,
sum(bookings) as BOOKINGS_RES, SAFE_CAST(Sum(revenue) as NUMERIC) AS REVENUE_RES, sum(leads) as LEADS_RES, 'BOOKINGS LEADS HIST' AS ORIGEN

from

(

select cast(date_trunc(timestamp, month) as date) as Fecha,

    -- HOMOLOGA CAMPAIGN FUNNEL
  CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
END AS CAMPAIGN_FUNNEL,
  
    -- CALCULA FUNNEL

    -- STAGE 1
    CASE 
        WHEN REGEXP_CONTAINS(
            
            (       CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BRAND_BOTB_Alkemy|BRAND_FR_Alkemy|BRAND_ER_Alkemy|BRAND_TEC_Alkemy)') 
             AND 
             
             (   CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
       WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END) = 'AWA' THEN 'TOFU'

    -- STAGE 2 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP|WEDDINGS)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
       WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'(?i)(Conde Nast|Fodors|Travel and Leisure|Teads|Taboola|TravelPulse|Smoot|Bridal Guide|PINTEREST|Bride Click|Bridalguide|The Knot)') 
    THEN 'TOFU'

-- STAGE 3

 WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'(?i)(DV360|TripAdvisor|META|CRITEO)') 
    THEN 'MOFU'

-- STAGE 4
WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(AO)') 
          
    AND REGEXP_CONTAINS(MEDIA, r'(?i)(PMAX)') 
    THEN 'BOFU'

-- STAGE 5 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BLACK FRIDAY|AO|TEST|WEDDINGS)') -------
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
       WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END )
                
                , r'(?i)(PRS|SEM GEN|SEM COMP)')
THEN 'MOFU'

--STAGE 6

      WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP|BLACK FRIDAY|AO|TEST|WEDDINGS)') -----
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
       WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 7

    WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(NEW YEAR)') 
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 8

WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
          
    AND REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
       WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 9

  WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CAMPAIGN LIKE '%GEN%' AND   REGEXP_CONTAINS(CAMPAIGN_TYPE, r'(?i)(Search|Google|MICROSOFT)') THEN 'SEM GEN'
        WHEN  REGEXP_CONTAINS(CAMPAIGN, r'(?i)(COMPETENCIA)') THEN 'SEM COMP'
        ELSE PLACEMENT 
    END )
                
                 , r'(?i)(PRS|SEM GEN|SEM COMP)')
THEN 'MOFU'

        ELSE 'NA'
    END AS FUNNEL,


 CAMPAIGN AS Campania, 
 
  -- HOMOLOGA CHANNEL
    CASE 
        WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        ELSE CAMPAIGN_TYPE 
    END AS  Canal,
 
  CASE WHEN BANNER_ADGROUP  IN ('META_BRAND_WED-FR_US_PRS_SOCIAL_STORIES_NA_CUI_WEDDINGS_NA_2502','META_BRAND_WED-ER_US_PRS_SOCIAL_STORIES_NA_CUI_WEDDINGS_NA_2502') THEN 'META - LEAD GEN' ELSE MEDIA END  as Medio, 
  
  count(*) as Bookings, sum(SALES) as Revenue, 0 as Leads  from  `primal-sunup-357522.TEC_EXCELLENCE_ADFORM_CONVERSION.TEC_BOOKINGS_LEADS_PM` 
where 
-- CAST(TIMESTAMP AS DATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) 
CAST(TIMESTAMP AS DATE) BETWEEN '2024-01-01' AND '2024-12-31'
and ORIGEN in ('RO','PCK')
group by 1,2,3,4,5,6)



-- WHERE FUNNEL <> 'NA'

group by 1,2,3,4,5 order by 1,2,3,4,5 asc;
