
insert into  `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Stg_P2C_Part`

SELECT *, DENSE_RANK() OVER (ORDER BY UserID ASC) AS P2C_ID_DL  FROM

(
SELECT 
CONCAT(C.IP,'_',C.CookieID) AS UserID
, C.IP
,C.CookieID
,cast( C.Timestamp AS date) as TIMESTAMP
, FORMAT_TIMESTAMP('%H:%M:%S', C.Timestamp) AS HORA
,1 AS IS_CONVERSION
,0 AS NUMERO_ORDEN
,0 P2C_ID
,C.CAMPAIGN
,  CASE 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(BRAND_BOTB_Alkemy|BRAND_FR_Alkemy|BRAND_ER_Alkemy)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'AWA' THEN 'TOFU'

    -- STAGE 2 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'\b(Conde Nast|Fodors|Travel and Leisure|Teads|Taboola|TravelPulse)\b') 
    THEN 'TOFU'

-- STAGE 3

 WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'\b(DV360|TripAdvisor|META)\b') 
    THEN 'MOFU'

-- STAGE 4
WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(AO)\b') 
          
    AND REGEXP_CONTAINS(MEDIA, r'\b(PMAX)\b') 
    THEN 'BOFU'

-- STAGE 5 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(BLACK FRIDAY|AO|TEST)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(PRS|SEM GEN)\b')
THEN 'MOFU'

--STAGE 6

      WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP|BLACK FRIDAY|AO|TEST)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(RTG|SEM BRAND)\b')
THEN 'BOFU'

-- STAGE 7

    WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(NEW YEAR)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
       -- WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
       -- WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(RTG|SEM BRAND)\b')
THEN 'BOFU'

-- STAGE 8

WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(WEDDINGS)\b') 
          
    AND REGEXP_CONTAINS(MEDIA, r'\b(Google AdWords)\b') 
    THEN 'BOFU'

-- STAGE 9

  WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(WEDDINGS)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(PRS)\b')
THEN 'MOFU'

        ELSE 'NA'
    END AS FUNNEL
,     CASE 
        WHEN C.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END AS CAMPAIGN_FUNNEL
    , C.CAMPAIGN_TYPE AS CANAL
    ,C.MEDIA AS MEDIO
    , cast( C.Timestamp AS date) as FECHA_CONVERSION
 FROM  `TEC_EXCELLENCE_ADFORM_CONVERSION.Transform_Adform_Conversion_Data` C
 where C.IS_BOOKING_CENTER IN ('false', 'NA')
 -- AND C.CookieID <> '0'
 and C.SALES is not null 
  and EXTRACT(YEAR FROM C.TIMESTAMP) = 2025 -- VAR AÑO ACTUAL
 and EXTRACT(MONTH FROM C.TIMESTAMP) = 01  -- VAR MES ANTERIOR
and EXTRACT(DAY FROM C.TIMESTAMP) BETWEEN 01 AND EXTRACT(DAY FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
-- and C.ip = '172.225.246.0' and C.CookieID = '-2994617711003804066'
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14

 UNION ALL

  SELECT 
CONCAT(CL.IP,'_',CL.CookieID) AS UserID
, CL.IP
,CL.CookieID
,cast( CL.Timestamp AS date) as TIMESTAMP
, FORMAT_TIMESTAMP('%H:%M:%S', CL.Timestamp) AS HORA
,0 AS IS_CONVERSION
,0 AS NUMERO_ORDEN
,0 P2C_ID
,CL.CAMPAIGN
,  CASE 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(BRAND_BOTB_Alkemy|BRAND_FR_Alkemy|BRAND_ER_Alkemy)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'AWA' THEN 'TOFU'

    -- STAGE 2 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'\b(Conde Nast|Fodors|Travel and Leisure|Teads|Taboola|TravelPulse)\b') 
    THEN 'TOFU'

-- STAGE 3

 WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'\b(DV360|TripAdvisor|META)\b') 
    THEN 'MOFU'

-- STAGE 4
WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(AO)\b') 
          
    AND REGEXP_CONTAINS(MEDIA, r'\b(PMAX)\b') 
    THEN 'BOFU'

-- STAGE 5 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(BLACK FRIDAY|AO|TEST)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(PRS|SEM GEN)\b')
THEN 'MOFU'

--STAGE 6

      WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP|BLACK FRIDAY|AO|TEST)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(RTG|SEM BRAND)\b')
THEN 'BOFU'

-- STAGE 7

    WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(NEW YEAR)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
       -- WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
       -- WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(RTG|SEM BRAND)\b')
THEN 'BOFU'

-- STAGE 8

WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(WEDDINGS)\b') 
          
    AND REGEXP_CONTAINS(MEDIA, r'\b(Google AdWords)\b') 
    THEN 'BOFU'

-- STAGE 9

  WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(WEDDINGS)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(PRS)\b')
THEN 'MOFU'

        ELSE 'NA'
    END AS FUNNEL
,     CASE 
        WHEN CL.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END AS CAMPAIGN_FUNNEL
    , CL.CAMPAIGN_TYPE AS CANAL
    ,CL.MEDIA AS MEDIO
    , cast( C.Timestamp AS date) as FECHA_CONVERSION
 FROM  `TEC_EXCELLENCE_ADFORM_CLICS_IMPRESSION.Transform_Adform_Clics` CL
  INNER JOIN (SELECT IP,COOKIEID,MAX(TIMESTAMP)AS TIMESTAMP,  FROM`TEC_EXCELLENCE_ADFORM_CONVERSION.Transform_Adform_Conversion_Data`
 WHERE 
  EXTRACT(YEAR FROM TIMESTAMP) = 2025 -- VAR AÑO ACTUAL
and EXTRACT(MONTH FROM TIMESTAMP) = 01 and 
EXTRACT(DAY FROM TIMESTAMP) BETWEEN 01 AND EXTRACT(DAY FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) GROUP BY 1,2 ) C
ON C.IP = CL.IP AND C.CookieID = CL.CookieID 
 WHERE CL.CookieID <> '0'
  and CAST(CL.Timestamp AS TIMESTAMP) BETWEEN DATE_SUB(CAST(C.TIMESTAMP AS TIMESTAMP), INTERVAL 60 DAY) AND C.TIMESTAMP
  
  UNION ALL

   SELECT distinct
CONCAT(IM.IP,'_',IM.CookieID) AS UserID
, IM.IP
,IM.CookieID
-- ,cast(IM.Timestamp as TIMESTAMP) as TIMESTAMP
,cast(FORMAT_TIMESTAMP('%Y-%m-%d', PARSE_TIMESTAMP('%Y-%m-%d', LEFT(IM.Timestamp,10)))as DATE) AS TIMESTAMP
,FORMAT_TIMESTAMP('%H:%M:%S', cast(FORMAT_TIMESTAMP('%Y-%m-%d %H:%M:00', PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LEFT(IM.Timestamp,19)))as TIMESTAMP)) AS HORA
,0 AS IS_CONVERSION
,0 AS NUMERO_ORDEN
,0 P2C_ID
,IM.CAMPAIGN
,  CASE 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(BRAND_BOTB_Alkemy|BRAND_FR_Alkemy|BRAND_ER_Alkemy)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'AWA' THEN 'TOFU'

    -- STAGE 2 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'\b(Conde Nast|Fodors|Travel and Leisure|Teads|Taboola|TravelPulse)\b') 
    THEN 'TOFU'

-- STAGE 3

 WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP)\b') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(MEDIA, r'\b(DV360|TripAdvisor|META)\b') 
    THEN 'MOFU'

-- STAGE 4
WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(AO)\b') 
          
    AND REGEXP_CONTAINS(MEDIA, r'\b(PMAX)\b') 
    THEN 'BOFU'

-- STAGE 5 
        WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(BLACK FRIDAY|AO|TEST)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(PRS|SEM GEN)\b')
THEN 'MOFU'

--STAGE 6

      WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(OPENING XCP|BLACK FRIDAY|AO|TEST)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(RTG|SEM BRAND)\b')
THEN 'BOFU'

-- STAGE 7

    WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(NEW YEAR)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
       -- WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
       -- WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(RTG|SEM BRAND)\b')
THEN 'BOFU'

-- STAGE 8

WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(WEDDINGS)\b') 
          
    AND REGEXP_CONTAINS(MEDIA, r'\b(Google AdWords)\b') 
    THEN 'BOFU'

-- STAGE 9

  WHEN REGEXP_CONTAINS(
            
            (    CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END)
            , r'\b(WEDDINGS)\b') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy)\b') THEN 'AWA'
        -- WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE PLACEMENT 
    END )
                
                , r'\b(PRS)\b')
THEN 'MOFU'

        ELSE 'NA'
    END AS FUNNEL
,     CASE 
        WHEN IM.CAMPAIGN LIKE '%XCP%' THEN 'OPENNING XCP'
        WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
        WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
        WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
        WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(AO|ao)\b') THEN 'AO'
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'\b(TEST|test)\b') THEN 'TEST_Alkemy'
        ELSE 'RESTO'
    END AS CAMPAIGN_FUNNEL
    , IM.CAMPAIGN_TYPE AS CANAL
    ,IM.MEDIA AS MEDIO
    ,cast( C.Timestamp AS date) as FECHA_CONVERSION
 FROM  `TEC_EXCELLENCE_ADFORM_CLICS_IMPRESSION.Transform_Adform_Impression` IM
 INNER JOIN (SELECT IP,COOKIEID,MAX(TIMESTAMP)AS TIMESTAMP,  FROM`TEC_EXCELLENCE_ADFORM_CONVERSION.Transform_Adform_Conversion_Data`
 WHERE EXTRACT(YEAR FROM TIMESTAMP) = 2025 -- VAR AÑO ACTUAL
and EXTRACT(MONTH FROM TIMESTAMP) = 01 and EXTRACT(DAY FROM TIMESTAMP) BETWEEN 01 AND EXTRACT(DAY FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) GROUP BY 1,2 ) C
ON C.IP = IM.IP AND C.CookieID = IM.CookieID 
 WHERE IM.CookieID <> '0'
  and CAST(IM.Timestamp AS TIMESTAMP) BETWEEN DATE_SUB(CAST(C.TIMESTAMP AS TIMESTAMP), INTERVAL 7 DAY) AND C.TIMESTAMP
 -- and  IM.ip = '172.225.246.0' and IM.CookieID = '-2994617711003804066'
   group by 
 1,2,3,4,5,6,7,8,9,10,11,12,13,14 order by 1,4,5 asc )
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14 order by 1,4,5 asc


 
