# PASO1: UNA VEZ LIMPIA LA BASE EN CSV SE DEBE TRUNCAR LA TABLA INTERMEDIA DE MEDIOS EXTERNOS:

TRUNCATE TABLE `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Medios_Externos` ;

# PASO 2: YA TRUNCADA LA TABLA INTERMEDIA DE MEDIOS EXTERNOS SE REALIZA LA CARGA DE LA BASE .CSV CON LA INTERFAZ DE CARGA DE BIGQUERY

# PASO 3: UNA VEZ CARGADA LA DATA DEL .CSV A LA TABLA INTERMEDIA DE MEDIOS EXTERNOS SE VALIDAN LOA REGISTROS CARGADOS:

SELECT COUNT(*) FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Medios_Externos` ;

# PASO 4: DESPUES DE VALIDAR LA CARGA CORRECTA EN LA TABLA INTERMEDIA DE MEDIOS EXTERNOS SE DEBE ELIMINAR LA CAPA DE MEDIOS EXTERNOS DEL MES EN CURSO EN LA TABLA PRINCIPAL

DELETE  from  `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` where fecha >= '2025-03-01' and origen = 'MEDIOS EXTERNOS';

# PASO 5 SE VALIDA QUE EFECTIVAMANTE YA NO HAYA CAPA DE MEDIOS EXTERNOS DEL MES EN CURSO. LA SIGUIENTE CONSULTA DEBERIA DAR 0 O BIEN NO REGRESAR RESULTADOS

SELECT COUNT(*)  from  `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` where fecha >= '2025-03-01' and origen = 'MEDIOS EXTERNOS';

# PASO 6: INTEGRAR LA DATA DE LA TABLA INTERMEDIA DE MEDIOS EXTERNOS A LA TABLA PRINCIPAL:

# INSERTA MEDIOS EXTERNOS
INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia`
SELECT 
FECHA,
FUNNEL,
CAMPANIA,
CANAL,
MEDIO,
OBJETIVO,
0 ASBUDGET_OBJ,
0 AS IMPRESIONES_OCJ,
0 AS VIEWS_OBJ,
0 AS CLICS_OBJ,
0 AS PARTICIPACIONES_OBJ,
0 AS BOOKINGS_OBJ,
0 AS REVENUE_OBJ,
0 AS LEADS_OBJ,
CAST(COSTO AS NUMERIC) AS BUDGET_RES,
IMPRESIONES AS IMPRESIONES_RES,
0 AS VIEWS_RES,
CLICS AS CLICS_RES,
0 AS PARTICIPACIONES_RES,
0 AS BOOKINGS_RES,
0 AS REVENUE_RES,
Leads AS LEADS_RES,
'MEDIOS EXTERNOS' AS ORIGEN,
 0 AS PP_LEADS_OBJ,
0 AS PP_LEADS_RES
 FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Medios_Externos`

 # PASO 7: LANZAR LAS HOMOLOGACIONES POST CARGA

update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Mixto' where CANAL = 'MIXTO';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Display' where CANAL = 'DISPLAY';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Video' where CANAL = 'VIDEO';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set MEDIO = 'META' where MEDIO IN ('FACEBOOK','Facebook');
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Search' where CANAL = 'SEARCH';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Search' where REGEXP_CONTAINS(CANAL, r'(?i)(MICROSOFT|GOOGLE)');
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Display' where REGEXP_CONTAINS(CANAL, r'(?i)(RTB)');
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set FUNNEL = 'TOFU'
WHERE FUNNEL = 'MOFU' AND CANAL = 'Display' and CAMPANIA = 'WEDDINGS' AND MEDIO = 'Bride Click';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set FUNNEL = 'TOFU'
WHERE FUNNEL = 'MOFU' AND CANAL = 'Display' and CAMPANIA = 'WEDDINGS' AND MEDIO = 'PINTEREST';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set FUNNEL = 'BOFU' where MEDIO IN ('MICROSOFTPMAX') AND
FECHA >= '2025-02-01';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set FUNNEL = 'BOFU', CANAL = 'Mixto',CAMPANIA = 'AO' where MEDIO IN ('MICROSOFTPMAX') AND
FECHA >= '2025-02-01';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set  CANAL = 'Social Media' WHERE MEDIO = 'META' AND CAMPANIA = 'BLACK FRIDAY' AND canal = 'Display';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set  CANAL = 'Mixto'where medio = 'PMAX' AND CANAL = 'Display';
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia`  set campania = 'AO' WHERE CAMPANIA = 'OPENING XCP' AND fecha >= '2025-03-01';

# PASO 8: VALIDAR CARGA OK. LA SIGUIENTE CONSULTA DEBE DAR EXACTAMENTE LAS MISMAS CANTIDADES. QUIERE DECIR QUE LOS DATOS DE LA TABLA INTERMEDIA SE CARGARON EXITOSAMENTE EN TABLA PRINCIPAL

SELECT 'TABLA INTERMEDIA' AS  ORIGEN , COUNT(*) AS REGISTROS FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Medios_Externos`  UNION ALL
SELECT 'TABLA PRINCIPAL' AS  ORIGEN , COUNT(*) AS REGISTROS  from  `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` where fecha >= '2025-03-01' and origen = 'MEDIOS EXTERNOS';

# CONFIRMAR QUE LA CAPA ESTA ACTUALIZADA :)
