  TRUNCATE TABLE `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Stg_P2C_Part`;

  -- SELECT * FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Stg_P2C_Part`; 197860

insert into  `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Stg_P2C_Part`

SELECT *, DENSE_RANK() OVER (ORDER BY UserID ASC) AS P2C_ID_DL  FROM

(
SELECT 
CONCAT(C.IP,'_',C.CookieID) AS UserID
, C.IP
,C.CookieID
,cast( C.Timestamp AS date) as TIMESTAMP
, FORMAT_TIMESTAMP('%H:%M:%S', C.Timestamp) AS HORA
,1 AS IS_CONVERSION
,0 AS NUMERO_ORDEN
,0 P2C_ID
,C.CAMPAIGN
,  

 -- CALCULA FUNNEL

    -- STAGE 1
    CASE 
        WHEN REGEXP_CONTAINS(
            
            (       CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BRAND_BOTB_Alkemy|BRAND_FR_Alkemy|BRAND_ER_Alkemy|BRAND_TEC_Alkemy)') 
             AND 
             
             (   CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE C.PLACEMENT 
    END) = 'AWA' THEN 'TOFU'

    -- STAGE 2 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE C.PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(C.MEDIA, r'(?i)(Conde Nast|Fodors|Travel and Leisure|Teads|Taboola|TravelPulse)') 
    THEN 'TOFU'

-- STAGE 3

 WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE C.PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(C.MEDIA, r'(?i)(DV360|TripAdvisor|META|CRITEO)') 
    THEN 'MOFU'

-- STAGE 4
WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(AO)') 
          
    AND REGEXP_CONTAINS(C.MEDIA, r'(?i)(PMAX)') 
    THEN 'BOFU'

-- STAGE 5 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BLACK FRIDAY|AO|TEST|WEDDINGS)') -------
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE C.PLACEMENT  
    END )
                
                , r'(?i)(PRS|SEM GEN)')
THEN 'MOFU'

--STAGE 6

      WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP|BLACK FRIDAY|AO|TEST|WEDDINGS)') -----
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE C.PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 7

    WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(NEW YEAR)') 
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE C.PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 8

WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
          
    AND REGEXP_CONTAINS(C.MEDIA, r'(?i)(Google AdWords)') 
    THEN 'BOFU'

-- STAGE 9

  WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN C.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(C.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN C.CAMPAIGN LIKE '%GEN%' AND C.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE C.PLACEMENT 
    END )
                
                , r'(?i)(PRS)')
THEN 'MOFU'

        ELSE 'NA'
    END AS FUNNEL   
,         
-- HOMOLOGA CAMPAIGN FUNNEL
  CASE
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN C.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN C.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN C.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN C.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN C.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN C.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(C.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
END AS CAMPAIGN_FUNNEL
    
,  -- HOMOLOGA CHANNEL
    CASE 
        WHEN C.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        WHEN C.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        ELSE CAMPAIGN_TYPE 
    END AS  CANAL


    ,C.MEDIA AS MEDIO
    , cast( C.Timestamp AS date) as FECHA_CONVERSION
 FROM  `TEC_EXCELLENCE_ADFORM_CONVERSION.Transform_Adform_Conversion_Data` C
 where C.IS_BOOKING_CENTER IN ('false', 'NA')
 -- AND C.CookieID <> '0'
 and C.SALES is not null 
  and EXTRACT(YEAR FROM C.TIMESTAMP) = EXTRACT(YEAR FROM CURRENT_DATE()) -- VAR AÑO ACTUAL
 and EXTRACT(MONTH FROM C.TIMESTAMP) = EXTRACT(MONTH FROM CURRENT_DATE())  -- VAR MES ANTERIOR
and EXTRACT(DAY FROM C.TIMESTAMP) BETWEEN 01 AND EXTRACT(DAY FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
-- and C.ip = '172.225.246.0' and C.CookieID = '-2994617711003804066'
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14

  UNION ALL

  SELECT 
CONCAT(CL.IP,'_',CL.CookieID) AS UserID
, CL.IP
,CL.CookieID
,cast( CL.Timestamp AS date) as TIMESTAMP
, FORMAT_TIMESTAMP('%H:%M:%S', CL.Timestamp) AS HORA
,0 AS IS_CONVERSION
,0 AS NUMERO_ORDEN
,0 P2C_ID
,CL.CAMPAIGN
,  

 -- CALCULA FUNNEL

    -- STAGE 1
    CASE 
        WHEN REGEXP_CONTAINS(
            
            (       CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BRAND_BOTB_Alkemy|BRAND_FR_Alkemy|BRAND_ER_Alkemy|BRAND_TEC_Alkemy)') 
             AND 
             
             (   CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE CL.PLACEMENT 
    END) = 'AWA' THEN 'TOFU'

    -- STAGE 2 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE CL.PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(CL.MEDIA, r'(?i)(Conde Nast|Fodors|Travel and Leisure|Teads|Taboola|TravelPulse)') 
    THEN 'TOFU'

-- STAGE 3

 WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE CL.PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(CL.MEDIA, r'(?i)(DV360|TripAdvisor|META|CRITEO)') 
    THEN 'MOFU'

-- STAGE 4
WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(AO)') 
          
    AND REGEXP_CONTAINS(CL.MEDIA, r'(?i)(PMAX)') 
    THEN 'BOFU'

-- STAGE 5 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BLACK FRIDAY|AO|TEST|WEDDINGS)') -------
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE CL.PLACEMENT 
    END )
                
                , r'(?i)(PRS|SEM GEN)')
THEN 'MOFU'

--STAGE 6

      WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP|BLACK FRIDAY|AO|TEST|WEDDINGS)') -----
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE CL.PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 7

    WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(NEW YEAR)') 
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE CL.PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 8

WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
          
    AND REGEXP_CONTAINS(CL.MEDIA, r'(?i)(Google AdWords)') 
    THEN 'BOFU'

-- STAGE 9

  WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN CL.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(CL.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN CL.CAMPAIGN LIKE '%GEN%' AND CL.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE CL.PLACEMENT 
    END )
                
                , r'(?i)(PRS)')
THEN 'MOFU'

        ELSE 'NA'
    END AS FUNNEL
    
    
,      
    -- HOMOLOGA CAMPAIGN FUNNEL
 CASE
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN CL.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN CL.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN CL.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN CL.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN CL.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(CL.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
END AS CAMPAIGN_FUNNEL
    
    
    ,  -- HOMOLOGA CHANNEL
    CASE 
        WHEN CL.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        WHEN CL.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        ELSE CL.CAMPAIGN_TYPE 
    END AS  CANAL


    ,CL.MEDIA AS MEDIO
    , cast( C.Timestamp AS date) as FECHA_CONVERSION
 FROM  `TEC_EXCELLENCE_ADFORM_CLICS_IMPRESSION.Transform_Adform_Clics` CL
  INNER JOIN (SELECT IP,COOKIEID,MAX(TIMESTAMP)AS TIMESTAMP,  FROM`TEC_EXCELLENCE_ADFORM_CONVERSION.Transform_Adform_Conversion_Data`
 WHERE 
  EXTRACT(YEAR FROM TIMESTAMP) = EXTRACT(YEAR FROM CURRENT_DATE())  -- VAR AÑO ACTUAL
and EXTRACT(MONTH FROM TIMESTAMP) = EXTRACT(MONTH FROM CURRENT_DATE()) and 
EXTRACT(DAY FROM TIMESTAMP) BETWEEN 01 AND EXTRACT(DAY FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) GROUP BY 1,2 ) C
ON C.IP = CL.IP AND C.CookieID = CL.CookieID 
 WHERE CL.CookieID <> '0'
  and CAST(CL.Timestamp AS TIMESTAMP) BETWEEN DATE_SUB(CAST(C.TIMESTAMP AS TIMESTAMP), INTERVAL 60 DAY) AND C.TIMESTAMP

  UNION ALL

   SELECT distinct
CONCAT(IM.IP,'_',IM.CookieID) AS UserID
, IM.IP
,IM.CookieID
-- ,cast(IM.Timestamp as TIMESTAMP) as TIMESTAMP
,cast(FORMAT_TIMESTAMP('%Y-%m-%d', PARSE_TIMESTAMP('%Y-%m-%d', LEFT(IM.Timestamp,10)))as DATE) AS TIMESTAMP
,FORMAT_TIMESTAMP('%H:%M:%S', cast(FORMAT_TIMESTAMP('%Y-%m-%d %H:%M:00', PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LEFT(IM.Timestamp,19)))as TIMESTAMP)) AS HORA
,0 AS IS_CONVERSION
,0 AS NUMERO_ORDEN
,0 P2C_ID
,IM.CAMPAIGN
,  


 -- CALCULA FUNNEL

    -- STAGE 1
    CASE 
        WHEN REGEXP_CONTAINS(
            
            (       CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BRAND_BOTB_Alkemy|BRAND_FR_Alkemy|BRAND_ER_Alkemy|BRAND_TEC_Alkemy)') 
             AND 
             
             (   CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE IM.PLACEMENT 
    END) = 'AWA' THEN 'TOFU'

    -- STAGE 2 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE IM.PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(IM.MEDIA, r'(?i)(Conde Nast|Fodors|Travel and Leisure|Teads|Taboola|TravelPulse)') 
    THEN 'TOFU'

-- STAGE 3

 WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP)') 
             AND 
             
             (  CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE IM.PLACEMENT 
    END) = 'PRS' 
    AND REGEXP_CONTAINS(IM.MEDIA, r'(?i)(DV360|TripAdvisor|META|CRITEO)') 
    THEN 'MOFU'

-- STAGE 4
WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(AO)') 
          
    AND REGEXP_CONTAINS(IM.MEDIA, r'(?i)(PMAX)') 
    THEN 'BOFU'

-- STAGE 5 
        WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(BLACK FRIDAY|AO|TEST|WEDDINGS)') -------
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE IM.PLACEMENT 
    END )
                
                , r'(?i)(PRS|SEM GEN)')
THEN 'MOFU'

--STAGE 6

      WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(OPENING XCP|BLACK FRIDAY|AO|TEST|WEDDINGS)') -----
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE IM.PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 7

    WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(NEW YEAR)') 
            AND  REGEXP_CONTAINS(
                ( CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE IM.PLACEMENT 
    END )
                
                , r'(?i)(RTG|SEM BRAND)')
THEN 'BOFU'

-- STAGE 8

WHEN REGEXP_CONTAINS(
            
            (    CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
          
    AND REGEXP_CONTAINS(IM.MEDIA, r'(?i)(Google AdWords)') 
    THEN 'BOFU'

-- STAGE 9

  WHEN REGEXP_CONTAINS(
            
            (   CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
    END)
            , r'(?i)(WEDDINGS)') 
            AND  REGEXP_CONTAINS(
                (  CASE 
        WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(BRAND_BOTB_Alkemy|BRAND_ER_Alkemy|BRAND_FR_Alkemy|BRAND_TEC_Alkemy)') THEN 'AWA'
        -- WHEN BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        -- WHEN BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(SEARCH)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%BRAND%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(MICROSOFT)') THEN 'SEM BRAND'
        WHEN IM.CAMPAIGN LIKE '%GENERICO%' AND REGEXP_CONTAINS(IM.CAMPAIGN_TYPE, r'(?i)(GOOGLE|MICROSOFT)') THEN 'SEM GEN'
        WHEN IM.CAMPAIGN LIKE '%GEN%' AND IM.CAMPAIGN_TYPE = 'Search' THEN 'SEM GEN'
        ELSE IM.PLACEMENT 
    END )
                
                , r'(?i)(PRS)')
THEN 'MOFU'

        ELSE 'NA'
    END AS FUNNEL
    
    
,     
 -- HOMOLOGA CAMPAIGN FUNNEL
 CASE
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)')  THEN 'OPENING XCP'
 WHEN IM.BANNER_ADGROUP LIKE '%_BF_%' THEN 'BLACK FRIDAY'
 WHEN IM.BANNER_ADGROUP LIKE '%BBDD-NN%' THEN 'NEW YEAR'
 WHEN IM.CAMPAIGN LIKE '%BRAND_FR_Alkemy%' THEN 'BRAND_FR_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_ER_Alkemy%' THEN 'BRAND_ER_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%BRAND_BOTB_Alkemy%' THEN 'BRAND_BOTB_Alkemy'
 WHEN IM.CAMPAIGN LIKE 'BRAND_TEC_Alkemy%' THEN 'BRAND_TEC_Alkemy'
 WHEN IM.CAMPAIGN LIKE '%WED%' THEN 'WEDDINGS'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(AO)') AND NOT REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(XCP)') THEN 'AO'
 WHEN REGEXP_CONTAINS(IM.CAMPAIGN, r'(?i)(TEST)') THEN 'TEST_Alkemy'
  ELSE 'RESTO'
END AS CAMPAIGN_FUNNEL
    
    
    ,  -- HOMOLOGA CHANNEL
    CASE 
        WHEN IM.BANNER_ADGROUP LIKE '%EMAIL%' THEN 'Email'
        WHEN IM.BANNER_ADGROUP LIKE '%VIDEO%' THEN 'Video'
        ELSE IM.CAMPAIGN_TYPE 
    END AS CANAL


    ,IM.MEDIA AS MEDIO
    ,cast( C.Timestamp AS date) as FECHA_CONVERSION
 FROM  `TEC_EXCELLENCE_ADFORM_CLICS_IMPRESSION.Transform_Adform_Impression` IM
 INNER JOIN (SELECT IP,COOKIEID,MAX(TIMESTAMP)AS TIMESTAMP,  FROM`TEC_EXCELLENCE_ADFORM_CONVERSION.Transform_Adform_Conversion_Data`
 WHERE EXTRACT(YEAR FROM TIMESTAMP) = EXTRACT(YEAR FROM CURRENT_DATE()) -- VAR AÑO ACTUAL
and EXTRACT(MONTH FROM TIMESTAMP) = EXTRACT(MONTH FROM CURRENT_DATE()) and EXTRACT(DAY FROM TIMESTAMP) BETWEEN 01 AND EXTRACT(DAY FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) GROUP BY 1,2 ) C
ON C.IP = IM.IP AND C.CookieID = IM.CookieID 
 WHERE IM.CookieID <> '0'
  and CAST(IM.Timestamp AS TIMESTAMP) BETWEEN DATE_SUB(CAST(C.TIMESTAMP AS TIMESTAMP), INTERVAL 7 DAY) AND C.TIMESTAMP
 -- and  IM.ip = '172.225.246.0' and IM.CookieID = '-2994617711003804066'
   group by 
 1,2,3,4,5,6,7,8,9,10,11,12,13,14 order by 1,4,5 asc )
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14 order by 1,4,5 asc;

 TRUNCATE TABLE `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Participaciones`;

 INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Participaciones`

SELECT FECHA_CONVERSION as Fecha,Funnel,CAMPAIGN_FUNNEL AS Campaign,Canal,Medio,count(distinct P2C_ID_DL) AS Paticipaciones FROM
`primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Stg_P2C_Part` where FUNNEL <> 'NA'
GROUP BY 1,2,3,4,5 ORDER BY FECHA_CONVERSION ASC;

# ELIMINA PARTICIPACIONES MES

DELETE FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` WHERE ORIGEN = 'PARTICIPACIONES'
AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());

# INSERTA PARTICIPACIONES

INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia`
SELECT 
FECHA,
FUNNEL,
CAMPAIGN AS CAMPANIA,
CANAL,
MEDIO,
'' AS OBJETIVO,
0 AS BUDGET_OBJ,
0 AS IMPRESIONES_OCJ,
0 AS VIEWS_OBJ,
0 AS CLICS_OBJ,
0 AS PARTICIPACIONES_OBJ,
0 AS BOOKINGS_OBJ,
0 AS REVENUE_OBJ,
0 AS LEADS_OBJ,
0 AS BUDGET_RES,
0 AS IMPRESIONES_RES,
0 AS VIEWS_RES,
0 AS CLICS_RES,
PARTICIPACIONES AS PARTICIPACIONES_RES,
0 AS BOOKINGS_RES,
0 AS REVENUE_RES,
0 AS  LEADS_RES,
'PARTICIPACIONES' AS ORIGEN
FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Participaciones` WHERE FUNNEL <> 'NA';

# HOMOLOGACIONES

update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Mixto' where CANAL = 'MIXTO' AND ORIGEN = 'PARTICIPACIONES' AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Display' where CANAL = 'DISPLAY' AND ORIGEN = 'PARTICIPACIONES'AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Video' where CANAL = 'VIDEO' AND ORIGEN = 'PARTICIPACIONES'AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set MEDIO = 'META' where MEDIO IN ('FACEBOOK','Facebook') AND ORIGEN = 'PARTICIPACIONES'AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Search' where CANAL = 'SEARCH' AND ORIGEN = 'PARTICIPACIONES'AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Search' where REGEXP_CONTAINS(CANAL, r'(?i)(MICROSOFT|GOOGLE)') AND ORIGEN = 'PARTICIPACIONES'AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set canal = 'Display' where REGEXP_CONTAINS(CANAL, r'(?i)(RTB)') AND ORIGEN = 'PARTICIPACIONES'AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
update `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia` set FUNNEL = 'TOFU'
WHERE
FUNNEL = 'MOFU' AND CANAL = 'Display' and CAMPANIA = 'WEDDINGS' AND MEDIO = 'Bride Click' AND  ORIGEN = 'PARTICIPACIONES'AND   EXTRACT(YEAR FROM FECHA) = EXTRACT(YEAR FROM CURRENT_DATE())
AND   EXTRACT(MONTH FROM FECHA) = EXTRACT(MONTH FROM CURRENT_DATE());
