# INSERTA MEDIOS EXTERNOS
INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia`
SELECT 
FECHA,
FUNNEL,
CAMPANIA,
CANAL,
MEDIO,
OBJETIVO,
0 ASBUDGET_OBJ,
0 AS IMPRESIONES_OCJ,
0 AS VIEWS_OBJ,
0 AS CLICS_OBJ,
0 AS PARTICIPACIONES_OBJ,
0 AS BOOKINGS_OBJ,
0 AS REVENUE_OBJ,
0 AS LEADS_OBJ,
CAST(COSTO AS NUMERIC) AS BUDGET_RES,
IMPRESIONES AS IMPRESIONES_RES,
0 AS VIEWS_RES,
CLICS AS CLICS_RES,
0 AS PARTICIPACIONES_RES,
0 AS BOOKINGS_RES,
0 AS REVENUE_RES,
0 AS LEADS_RES,
'MEDIOS EXTERNOS' AS ORIGEN,
 FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Medios_Externos`

# INSETRA BOOKINGS LEADS

INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia`
SELECT 
FECHA,
FUNNEL,
Campaign_funnel AS CAMPANIA,
CANAL,
MEDIO,
'' AS OBJETIVO,
0 AS BUDGET_OBJ,
0 AS IMPRESIONES_OCJ,
0 AS VIEWS_OBJ,
0 AS CLICS_OBJ,
0 AS PARTICIPACIONES_OBJ,
0 AS BOOKINGS_OBJ,
0 AS REVENUE_OBJ,
0 AS LEADS_OBJ,
0 AS BUDGET_RES,
0 AS IMPRESIONES_RES,
0 AS VIEWS_RES,
0 AS CLICS_RES,
0 AS PARTICIPACIONES_RES,
BOOKINGS AS BOOKINGS_RES,
CAST(REVENUE AS NUMERIC) AS REVENUE_RES,
LEADS AS LEADS_RES,
'BOOKINGS LEADS' AS ORIGEN
FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Bookings_Leads`

# INSERTA IMPRESSIONS CLICS

INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia`
SELECT
FECHA,
FUNNEL,
CAMPANIA,
CANAL,
MEDIO,
'' AS OBJETIVO,
0 AS BUDGET_OBJ,
0 AS IMPRESIONES_OCJ,
0 AS VIEWS_OBJ,
0 AS CLICS_OBJ,
0 AS PARTICIPACIONES_OBJ,
0 AS BOOKINGS_OBJ,
0 AS REVENUE_OBJ,
0 AS LEADS_OBJ,
0 AS BUDGET_RES,
CAST(IMPRESIONS AS INT64) AS IMPRESIONES_RES,
0 AS VIEWS_RES,
CAST(CLICS AS INT64) AS CLICS_RES,
0 AS PARTICIPACIONES_RES,
0 AS BOOKINGS_RES,
0 AS REVENUE_RES,
0 AS LEADS_RES,
'IMPRESSIONS CLICS' AS ORIGEN
from `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Impressions_Clics``primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Impressions_Clics`

# INSERTA PARTICIPACIONES

INSERT INTO `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Objetivos_dia`
SELECT 
FECHA,
FUNNEL,
CAMPAIGN AS CAMPANIA,
CANAL,
MEDIO,
'' AS OBJETIVO,
0 AS BUDGET_OBJ,
0 AS IMPRESIONES_OCJ,
0 AS VIEWS_OBJ,
0 AS CLICS_OBJ,
0 AS PARTICIPACIONES_OBJ,
0 AS BOOKINGS_OBJ,
0 AS REVENUE_OBJ,
0 AS LEADS_OBJ,
0 AS BUDGET_RES,
0 AS IMPRESIONES_RES,
0 AS VIEWS_RES,
0 AS CLICS_RES,
PARTICIPACIONES AS PARTICIPACIONES_RES,
0 AS BOOKINGS_RES,
0 AS REVENUE_RES,
0 AS  LEADS_RES,
'PARTICIPACIONES' AS ORIGEN
FROM `primal-sunup-357522.TEC_LAYOUT_OBJETIVOS.TEC_Participaciones` ;
